name: 'Upload Zipped Source Code on Release'

on:
  release:
    types:
      - created

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # steps for building assets
      - name: Create Zip file for /src
        run: zip -r src.zip src

      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: src.zip
